### ISSUE TITLE
Styling Codeblocks (Fenced Code)

### ISSUE THREAD

**Issue by EvanZhouDev** [lezer-parser/markdown#41] opened 2024-04-07 04:30 UTC
After much looking around, I haven't been able to find an answer, so I hope that someone can help me out here 😅

I'm trying to style Markdown code blocks in my code. I have found mentions of `FencedCode` in various places, but I have not figured out how to associate this `FencedCode` to anything.

What I want is for code blocks (denoted by triple backticks) to have a background color, and ideally a border radius as well in a WYSIWYG editor, not unlike the one shown below.

<img width="684" alt="image" src="https://github.com/lezer-parser/markdown/assets/62189478/a23c294d-e3a8-423e-b858-a332af765ace">

This was done through https://github.com/davidmyersdev/ink-mde, but it lacks the fine grained control I want over CodeMirror.

I believe the way that Ink MDE does it is that somehow all code in CodeBlocks have the `.cm-codeblock` class, and the top and bottom of the codeblock have their own classes so that it can be given a border radius.

I've been looking for more than an hour now for a solution (and I'm not even sure this is the right place to ask about this...), but any help is appreciated. Thank you!

**Comment by marijnh** [comment] 2024-04-07 07:14
You can't have an element wrapping your entire code block—the structure of editor content is a sequence of lines. You could use [line decorations](https://codemirror.net/docs/ref/#view.Decoration^line) to style all the lines that make up the code block in a different way. The approach to take would be to iterate through the [syntax tree](https://codemirror.net/docs/ref/#language.syntaxTree) for the visible content in a plugin to create these decorations every time the document or viewport changes.

Closing this, since it's not a bug report. The [forum](https://discuss.codemirror.net) is a better place for questions.

**Closed by marijnh** 2024-04-07 07:14 UTC

**Comment by EvanZhouDev** [comment] 2024-04-10 02:25
@marijnh I understand. Can you show me an example of code to do this though? I am not understanding how this works...
